# ------------------------------------------------------------------------------
# Example Config file for orthorectify-utility
# 
#   This file follows yaml formatting with keys as described below
#
# ------------------------------------------------------------------------------


# --- input-data-source [STRING]------------------------------------------------
# Input data source describes original source of data
# Valid Values are:
#   digital-globe:
#     data supplied with this key has a directory structure that
#     matches the format of data as downloaded from digital globe.
#     With digital globe data rpc information is used in orthorectification
#   reflectance:
#     reflectance data output from radiometric-calibration-utility.py
#   csv:
#     use this method if manual-input method is used in 
#     radiometric-calibration-utility.py 
# 
# other data sources are not supported, this key was mostly included 
# to help future proof the program.
# ------------------------------------------------------------------------------
input-data-source: reflectance

# --- input-data-directory [PATH]-----------------------------------------------
# Path to root of input data 
#   or 
# Path to csv file report from calibration utility
# ------------------------------------------------------------------------------
input-data: data/iceroad/reflectance-data/

# --- input-data-directory [PATH]-----------------------------------------------
# Path (relative to `input-directory`)  with wildcard that defines any 
# subdirectories that contain data.
# 
# Can be omitted if input-data-source is reflectance
# ------------------------------------------------------------------------------
# input-sub-dir-format: iceroad_*


# DEM --------------------------------------------------------------------------

# --- dem [PATH]----------------------------------------------------------------
# Path to DEM file used for ortho-rectification
# ------------------------------------------------------------------------------
dem: arctic-dem/iceroad-dem.vrt


# OTHER SETTING ----------------------------------------------------------------

# --- crs [STRING]--------------------------------------------------------------
# CRS for output files. Either a WTK crs string or DEM_CRS to use the crs of the
# DEM
# ------------------------------------------------------------------------------
crs: DEM_CRS


# OUTPUTS ----------------------------------------------------------------------

# --- orthorectified-directory [path]-------------------------------------------
# Path to save output files
# ------------------------------------------------------------------------------
orthorectified-directory: orthorectified-data

# --- orthorectified-directory [yes/no]-----------------------------------------
# If 'yes' out data is divided into subdirectories based on date/time of 
# acquisition. If 'no' all data is stored in root of `orthorectified-directory`
# ------------------------------------------------------------------------------
output-sub-directories: yes

# --- report-file [path]--------------------------------------------------------
# Path to save a report csv file that maps the input files to the output files
# ------------------------------------------------------------------------------
report-file: orthorectification-report.csv
